### ISSUE TITLE
Cannot Implement The Library

### ISSUE THREAD

**Issue by YovanggaAnandhika** [AndroidStudyOpenSource/tovuti#1]
Failed to resolve: com.androidstudy:tovuti:0.0.1

**Comment by Thien658jjh** [comment]
same @YovanggaAnandhika

**Comment by evawanini** [comment]
Failed to resolve: com.androidstudy:tovuti:0.0.1

**Comment by JobGetabu** [comment]
Failed to resolve: com.androidstudy:tovuti:0.0.1 too

**Comment by ahsan7766** [comment]
Failed to resolve: com.androidstudy:tovuti:0.0.1 too

**Comment by YovanggaAnandhika** [comment]
i get a solution @ahsan7766 @JobGetabu  @evawanini @Thien658jjh 
change "com.androidstudy:tovuti:0.0.1" to "com.amitshekhar.android:android-networking:1.0.2"

**Comment by ManishAndroidIos** [comment]
ERROR: Failed to resolve: com.androidstudy:tovuti:0.0.1

**Comment by YovanggaAnandhika** [comment]
@ManishAndroidlos, just rename "com.androidstudy:tovuti:0.0.1" to "com.amitshekhar.android:android-networking:1.0.2"

**Comment by DreamStarcoder** [comment]
change with this implementation 'com.github.jumadeveloper:networkmanager:0.0.2'
